# Generated by Django 2.2.14 on 2021-11-19 17:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logger', '0020_submission_counter_timestamp_as_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={},
        ),
        migrations.AlterModelOptions(
            name='xform',
            options={'ordering': ('id_string',), 'permissions': (('report_xform', 'Can make submissions to the form'), ('transfer_xform', 'Can transfer form ownership.'), ('validate_xform', 'Can validate submissions'), ('delete_data_xform', 'Can delete submissions')), 'verbose_name': 'XForm', 'verbose_name_plural': 'XForms'},
        ),
        migrations.AlterUniqueTogether(
            name='xform',
            unique_together={('user', 'id_string')},
        ),
    ]
